docs/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView

from docs.views import SubdivisionView, LeadingView, IndexView

app_name = 'docs'
urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
   url(r'^(?P<leading_slug>)$', LeadingView.as_view(template_name='docs/documents.html'), name='leading_detail'),
    # url(r'^test', TemplateView.as_view(template_name='docs/test.html'), name='test'),
    url(r'^(?P<subdivision_slug>)', SubdivisionView.as_view(), name='instr'),
]

insite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('main.urls')),
    url(r'^docs/', include('docs.urls')),


    url(r'^admin/', admin.site.urls),
]

main/urls.py
from django.conf.urls import url

from main.views import MainPageView

urlpatterns = [
    url(r'^$', MainPageView, name='main'),
]

docs/models.py
from django.db import models
from tinymce.models import HTMLField

class Subdivision(models.Model):
    title = models.CharField(max_length=100, verbose_name='Назва підрозділу')
    slug = models.SlugField(verbose_name=r"Адресна строка", max_length=255, unique=True,
                           help_text='Унікальне значення в адресній строці, добавляється автоматично.')

    class Meta:
        verbose_name = u"Підрозділ"
        verbose_name_plural = u"Підрозділи"
        ordering = [ 'title', ]

    def __str__(self):
        return self.title

class Leading(models.Model):
    DOC_TYPE_CHOICES = (
        ('INSTR', 'Інструкція'),
        ('POL', 'Положення'),
        ('PROC', 'Процедура'),

    )
    doc_type_choices = models.CharField(max_length=5,
                                      choices=DOC_TYPE_CHOICES,
                                      default='INSTR',verbose_name='Тип документу', help_text='Оберіть тип документу(інструкція, положення, процедура)')
    subdivision = models.ManyToManyField(Subdivision, verbose_name='Підрозділ')
    title = models.CharField(max_length=100, verbose_name='Назва')
    slug = models.SlugField(verbose_name=r"Адресна строка", max_length=255, unique=True,
                            help_text='Унікальне значення в адресній строці, добавляється автоматично.')
    text = HTMLField(verbose_name='Зміст')

    class Meta:
        verbose_name = u"Документ"
        verbose_name_plural = u"Документи"
        ordering = ['title',]

    def get_absolute_url(self):
        from django.core.urlresolvers import reverse
        return reverse('leading_detail', kwargs={'slug':self.slug, 'subdivision':self.subdivision } )

    def __str__(self):
        return self.title

class Docs(models.Model):
    title = models.CharField(max_length=100, verbose_name='Назва документу')
    file = models.FileField(verbose_name='Файл для скачування', upload_to='docs/')

    class Meta:
        abstract = True
        verbose_name = u"Документ"
        verbose_name_plural = u"Документи"

    def __str__(self):
        return self.title

class DocsLeading(Docs):
    leading = models.ForeignKey(Leading, on_delete=models.CASCADE)

main/models.py
from django.db import models

# Create your models here.

docs/views.py
from django.views import generic
from docs import apps
from django.shortcuts import get_object_or_404

from .models import Subdivision, Leading, DocsLeading

class IndexView(generic.ListView):
    template_name = 'docs/category_list.html'
    context_object_name = 'latest_subdivisions_list'
    queryset = Subdivision.objects.all()

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        app_docs = apps.InstrConfig.verbose_name
        context['app_docs'] = app_docs
        return context

class LeadingView(generic.DetailView):
    template_name = 'docs/documents.html'
    model = Leading
    context_object_name = 'leading_detail'

    def get_context_data(self, **kwargs):
        context = super(LeadingView, self).get_context_data(**kwargs)
        #        context['subdivision'] = self.subdivision.get().title
        context['leading_slug'] = self.request.path.split('/')[-1]
        return context

class SubdivisionView(generic.ListView):
    model = Subdivision
    template_name = 'docs/documents_list.html'
    context_object_name = 'instr'

    # def get_queryset(self):
    #     sdivision = Subdivision.objects.filter(slug=self.request.path.split('/')[-2])

    def get_context_data(self, **kwargs):
        context = super(SubdivisionView, self).get_context_data(**kwargs)
#        context['subdivision'] = self.subdivision.get().title
        context['subdivision_slug'] = self.request.path.split('/')[-1]
        context['subdivision_title'] = Subdivision.objects.filter(slug=self.request.path.split('/')[-1]).get()
        # context['subdivision'] = Subdivision.objects.select_related().get(slug=self.request.path.split('/')[-2])
        app_docs = apps.InstrConfig.verbose_name
        context['app_docs'] = app_docs
        # context['latest_instr_list'] = Leading.objects.filter(doc_type_choices='INSTR').filter(subdivision = self.subdivision)
        # context['latest_instr_list'] = Leading.objects.filter(doc_type_choices='INSTR')
        context['latest_instr_list'] = Leading.objects.filter(doc_type_choices='INSTR').filter(subdivision=Subdivision.objects.filter(slug=self.request.path.split('/')[-1]))
        context['latest_pol_list'] = Leading.objects.filter(doc_type_choices='POL').filter(subdivision=Subdivision.objects.filter(slug=self.request.path.split('/')[-1]))
        context['latest_proc_list'] = Leading.objects.filter(doc_type_choices='PROC').filter(subdivision=Subdivision.objects.filter(slug=self.request.path.split('/')[-1]))
        return context

main/views.py
from django.shortcuts import render
from docs import apps

def MainPageView(request):
    app_docs = apps.InstrConfig.verbose_name
    context = {'app_docs': app_docs}
    return render(request, 'redirect/index.html', context)

docs/templates/docs/category_list.html
{% extends 'docs/index.html' %}
{% block bread %}
    <a href={% url 'main' %}>Головна</a> > {{ app_docs }}
{% endblock %}
{% block category_list %}
    {% if latest_subdivisions_list %}
        <ul>
            {% for divisions in latest_subdivisions_list %}
                <li><a href="{% url 'docs:index' %}{{ divisions.slug }}">{{ divisions.title }}</a></li>
            {% endfor %}
        </ul>
    {% else %}
        <p>Немає підрозділів</p>
    {% endif %}
{% endblock category_list %}

docs/templates/docs/documents.html
{% extends 'docs/index.html' %}
ttt
{% block doc %}
    {{ leading_slug }}
{% endblock doc %}

docs/templates/docs/documents_list.html
{% extends 'docs/index.html' %}
{% block bread %}
    <a href={% url 'main' %}>Головна</a> > <a href={% url 'docs:index' %}>{{ app_docs }}</a> > {{ subdivision_title }}
{% endblock %}
{% block category_list %}
    <h3>Документація по підрозділу: <strong>{{ subdivision_title }}</strong></h3>
    <h4>Посадові інструцкції</h4>
    {% if latest_instr_list %}
        <ul>
        {% for instr in latest_instr_list %}
            <li><a href={{ instr.slug }}>{{ instr.title }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>Немає інструкцій для цього підрозділу</p>
    {% endif %}

    <h4>Положення</h4>
    {% if latest_pol_list %}
        <ul>
        {% for pol in latest_pol_list %}
            <li><a href={{ pol.slug }}>{{ pol.title }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>Немає положень для цього підрозділу</p>
    {% endif %}

    <h4>Процедури</h4>
    {% if latest_proc_list %}
        <ul>
        {% for proc in latest_proc_list %}
            <li><a href={{ proc.slug }}>{{ proc.title }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>Немає процедур для цього підрозділу</p>
    {% endif %}
{% endblock %}

docs/templates/docs/test.html
{% extends 'docs/index.html' %}
{% block doc %}
<h1>QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ</h1>
{% endblock doc %}

docs/templates/instr/index.html
{% if latest_subdivisions_list %}
    <ul>
    {% for subdivision in latest_subdivisions_list %}
        <li><a href="/instrukciy/{{ subdivision.slug }}/">{{ subdivision.title }}</a></li>

    {% endfor %}
    </ul>
{% else %}
    <p>Немає підрозділів</p>
{% endif %}

main/templates/redirect/index.html
{% extends 'base.html' %}
{% block title %}{{ app_docs }}{% endblock %}
{% block site %}
    <br>
        <li><a href={% url 'docs:index' %}>{{ app_docs }}</a></li>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="uk-ua">
<head>
    {% load staticfiles %}
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
{% block bread %}<a href={% url 'main' %}>Головна</a>{% endblock %}
<br>
{% block site %}{% endblock %}
</body>
</html>